version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: sptm-keycloak-new 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080" 
    command: start-dev
  
  postgres:
    image: postgres:15
    container_name: sptm-postgres
    environment:
      POSTGRES_DB: sptmdb
      POSTGRES_USER: sptmuser
      POSTGRES_PASSWORD: sptmpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data




volumes:
  postgres_data:
